SLEMA-61 architecture refactor without gui (deleting/editing medicine, crud on notifications)
pikol93/PG_SLEMA pull request #10
Opened 2023-12-06 18:00 UTC by Sladamos

2023-12-06 19:53 UTC, pikol93 requested changes
Trzeba na pewno wymyślić coś z tymi zakomentowanymi plikami.
Daj znać też co myślisz o tych metodach async.

2023-12-06 19:53 UTC, pikol93 commented on lib/features/medicine/application/service/notification_scheduling_service.dart
> +            (int id, String? title, String? body, String? payload) async {});
Można tu utworzyć nową metodę w tej klasie zamiast tworzyć lambdę.

2023-12-06 19:53 UTC, pikol93 commented on lib/features/medicine/application/service/notification_scheduling_service.dart
> +  // Shows notification when executed
Tu pozostał jakiś zakomentowany kod

2023-12-06 19:53 UTC, pikol93 commented on lib/features/medicine/application/service/notification_service.dart
> +  void addNotification(Notification notification) async {
Tu coś mi nie pasuje, bo według sygnatury metody jest ona asynchroniczna, ale zwraca `void` i nie ma żadnego `await`. Jak to tutaj działa?

2023-12-06 19:53 UTC, pikol93 commented on lib/features/medicine/data/dto/medicine_dto.dart
> +  static String medicineListSharedPrefKey = 'medicines';
To nie jest błąd, ale osobiście preferuję statyczne zmienne oddzielone pustą linią od zmiennych instancji dla jasności. ;)

2023-12-06 19:53 UTC, pikol93 commented on lib/features/medicine/data/dto/notification_dto.dart
> +  static String notificationListSharedPrefKey = 'notifications';
`const` nie przejdzie? Jeżeli nie, to dałbym `final`.

2023-12-06 19:53 UTC, pikol93 commented on lib/features/medicine/data/repository/shared_preferences_medicine_repository.dart
> +  SharedPreferencesMedicineRepository(this.medicineConverter);
To jest wywołanie? Definicja?

2023-12-06 19:53 UTC, pikol93 commented on lib/features/medicine/domain/notification.dart
> +enum Frequency { singular, daily, everyTwoDays, everyThreeDays }
To bym wyrzucił do innego pliku

2023-12-06 19:53 UTC, pikol93 commented on lib/features/medicine/presentation/widget/formWidgets/date_input.dart
> +// COMMENTED BECAUSE PROBABLY WOULD BE USEFUL FOR CODE STEALING
Kiedy usuwamy?

Szczerze jestem przeciwnikiem pozostawiania zakomentowanego kodu. Nawet jeżeli mamy z niego kraść później. Zdecydowanie lepiej byłoby cofnąć się do tagu i wtedy brać kod.

2023-12-06 19:53 UTC, pikol93 commented on lib/features/medicine/presentation/widget/formWidgets/repeat_radio_input_list.dart
> +// COMMENTED BECAUSE PROBABLY WOULD BE USEFUL FOR CODE STEALING
W branży nazywa się to code reuse ;)

2023-12-06 19:53 UTC, pikol93 commented on lib/features/medicine/presentation/widget/formWidgets/text_input.dart
> +      {super.key,
Coś tu formatter się pomylił chyba?

2023-12-06 19:53 UTC, pikol93 commented on lib/utils/id/integer_id_generator.dart
> +  static const maxInt = -1 >>> 1;
To jest akurat problematyczne i niekoniecznie będzie się dobrze zachowywać na wszystkich systemach.


https://stackoverflow.com/questions/50429660/is-there-a-constant-for-max-min-int-double-value-in-dart

2023-12-06 20:09 UTC, Sladamos commented on lib/features/medicine/application/service/medicine_service.dart
> +  void addMedicine(Medicine medicine) {
Racja te zakomentowane zostawilem zeby potem nie szukać jakby to miało być potrzebne.. Jak np skonczymy formularz czy notyfikacje to je wywalic.. Co do tego async zapomnialem ich dodać tam w serwisie chyba w drugim dodałem. Nie wiem co to fire and forget

2023-12-06 20:10 UTC, Sladamos commented on lib/features/medicine/application/service/notification_scheduling_service.dart
> +            (int id, String? title, String? body, String? payload) async {});
Ukradlem z yt XD

2023-12-06 20:12 UTC, Sladamos commented on lib/features/medicine/application/service/notification_service.dart
> +  void addNotification(Notification notification) async {
Nie do konca wiem. On czasami dziala tak, ze void to taki future ale nie mozesz na niego zaczekac xD Zmienie to na Future bo to sluszne akurat, ale await z tym mam problem -> czy on powinein czekac na te metody z repo czy nie

2023-12-06 20:12 UTC, Sladamos commented on lib/features/medicine/data/dto/medicine_dto.dart
> +  static String medicineListSharedPrefKey = 'medicines';
Zmień formatter zeby dodawał światło

2023-12-06 20:12 UTC, Sladamos commented on lib/features/medicine/data/dto/notification_dto.dart
> +  static String notificationListSharedPrefKey = 'notifications';
Mozna dodać, analyzer nie podpowiadał warto mu to dodać

2023-12-06 20:12 UTC, Sladamos commented on lib/features/medicine/data/repository/shared_preferences_medicine_repository.dart
> +  SharedPreferencesMedicineRepository(this.medicineConverter);
Konstruktor xD

2023-12-06 20:13 UTC, Sladamos commented on lib/features/medicine/domain/notification.dart
> +enum Frequency { singular, daily, everyTwoDays, everyThreeDays }
Mądre tak zrobie

2023-12-06 20:13 UTC, Sladamos commented on lib/features/medicine/presentation/widget/formWidgets/date_input.dart
> +// COMMENTED BECAUSE PROBABLY WOULD BE USEFUL FOR CODE STEALING
Usuwamy jak będzie GUI zrobione jakies z którego będzie się dało kraść inne rzeczy xd ale mozna to wywalic

2023-12-06 20:13 UTC, Sladamos commented on lib/features/medicine/presentation/widget/formWidgets/repeat_radio_input_list.dart
> +// COMMENTED BECAUSE PROBABLY WOULD BE USEFUL FOR CODE STEALING
ja jestem zlodziejaszkiem pierwszorzędnym

2023-12-06 20:14 UTC, Sladamos commented on lib/utils/id/integer_id_generator.dart
> +  static const maxInt = -1 >>> 1;
double.infinity as int proponujesz?

2023-12-06 20:55 UTC, pikol93 commented on lib/features/medicine/application/service/medicine_service.dart
> +  void addMedicine(Medicine medicine) {
Fire and forget czyli odpalasz asynchroniczną funkcję i o niej zapominasz. Funkcja odpalająca i funkcja asynchroniczna obie zaczynają działać. W tym przypadku będzie to na przykład dodanie leku, bo skoro nie potrzebujemy informacji zwrotnej o wykonanej operacji, to nie musimy czekać na zakończenie wykonywania.

2023-12-06 21:01 UTC, pikol93 commented on lib/utils/id/integer_id_generator.dart
> +  static const maxInt = -1 >>> 1;
To dla mnie śmierdzi jak UB.
![image](https://github.com/pikol93/PG_SLEMA/assets/40030490/b70748c4-fb64-4b2d-a8f0-af310fac3eda)

Dałbym jakąś arbitralnie dużą liczbę i miałbym to gdzieś.
![image](https://github.com/pikol93/PG_SLEMA/assets/40030490/aee6411f-85d5-429f-8ffd-4aba59d9c798)

2023-12-06 21:05 UTC, pikol93 commented on lib/features/medicine/data/dto/medicine_dto.dart
> +  static String medicineListSharedPrefKey = 'medicines';
Formatter w dart jest na tyle ograniczony, że nie ma takiej możliwości.

(formatter w rust pewnie to ma coś takiego)

2023-12-06 21:09 UTC, pikol93 commented on lib/features/medicine/data/repository/shared_preferences_medicine_repository.dart
> +  SharedPreferencesMedicineRepository(this.medicineConverter);
XD

2023-12-09 11:45 UTC, pikol93 approved these changes
Jest git. Merguję od razu bo domergowałem maina do SLEMA-61.

2023-12-09 11:45 UTC, merged