SLEMA-66 Zaimplementowanie kalendarze dla zakładki z dietą.
pikol93/PG_SLEMA pull request #11
Opened 2023-12-09 22:24 UTC by amddaa

2023-12-09 22:25 UTC, amddaa commented
Parę dodatkowych słów: https://pgslema.atlassian.net/l/cp/8EmPGXvd

2023-12-11 23:59 UTC, Sladamos requested changes

2023-12-11 23:59 UTC, Sladamos commented on lib/features/diet/presentation/controller/calendar_controller.dart
> +    firstDate = DateTime.now().subtract(const Duration(days: 365 * 5));
Magic numbers

2023-12-12 13:10 UTC, Sladamos commented on lib/features/diet/presentation/controller/calendar_controller.dart
> +    firstDate = DateTime.now().subtract(const Duration(days: 365 * 5));
Dodatkowo, proponuje zamiast 365 * lata zrobić 12 * miesiące??? Żeby nie przeładować sobie danych z daniami, trzymajmy np pół roku w tył i tyle.

2023-12-12 14:30 UTC, amddaa commented on lib/features/diet/presentation/controller/calendar_controller.dart
> +    firstDate = DateTime.now().subtract(const Duration(days: 365 * 5));
Poprawiłem to i zmieniłem na miesiące tak jak napisałeś.

2023-12-12 16:15 UTC, Sladamos approved these changes

2023-12-12 16:15 UTC, merged