SLEMA-79 Created the add_assessment_screen
pikol93/PG_SLEMA pull request #27
Opened 2024-01-20 18:51 UTC by pikol93

Jest wygląd i struktura UI. Nie ma funkcjonalności. Po kliknięciu w buttony nie dzieje się nic oprócz printowania wiadomości w logu. Rodzielone zostanie to na osobne zadania.

2024-01-21 19:32 UTC, Sladamos requested changes

2024-01-21 19:32 UTC, Sladamos commented on SlemaForAndroid/lib/features/well_being_assessment/data/symptom_type.dart
Konstruktor i pola miejscami do zamienienia

2024-01-21 19:32 UTC, Sladamos commented on SlemaForAndroid/lib/features/well_being_assessment/presentation/widget/forms/common/assessment_form_title.dart
Konstruktor

2024-01-21 19:32 UTC, Sladamos commented on SlemaForAndroid/lib/features/well_being_assessment/presentation/widget/forms/common/assessment_subtitle_text.dart
Konstruktor

2024-01-21 19:32 UTC, Sladamos commented on SlemaForAndroid/lib/features/well_being_assessment/presentation/widget/forms/sleep/assessment_sleep_duration_button.dart
Konstruktor, moze zamienic Function na ValueSetter czy cos takiego?

2024-01-21 19:32 UTC, Sladamos commented on SlemaForAndroid/lib/features/well_being_assessment/presentation/widget/forms/sleep/assessment_sleep_duration_buttons_row.dart
Konstruktor, brak callbacka?

2024-01-21 19:32 UTC, Sladamos commented on SlemaForAndroid/lib/features/well_being_assessment/presentation/widget/forms/symptoms/assessment_symptom_entry.dart
Konstruktor, wymienilbym Function na jakies inne callbacki.

2024-01-21 19:32 UTC, Sladamos commented on SlemaForAndroid/lib/features/well_being_assessment/presentation/widget/forms/symptoms/assessment_symptoms_change_value_button.dart
Konstruktor

2024-01-21 19:32 UTC, Sladamos commented on SlemaForAndroid/lib/features/well_being_assessment/presentation/widget/forms/symptoms/assessment_symptoms_form.dart
Wiecej niz 1 klasa w pliku

2024-01-21 19:32 UTC, Sladamos commented on SlemaForAndroid/lib/features/well_being_assessment/presentation/widget/forms/well_being/assessment_well_being_selector_variant.dart
Konstruktor

2024-01-21 19:32 UTC, Sladamos commented on SlemaForAndroid/lib/features/well_being_assessment/presentation/widget/forms/common/assessment_entry.dart
Czemu child nullable?

2024-01-21 19:32 UTC, Sladamos commented on SlemaForAndroid/lib/features/well_being_assessment/presentation/widget/forms/common/assessment_button.dart
Konstruktor

2024-01-21 19:32 UTC, Sladamos commented on SlemaForAndroid/lib/features/well_being_assessment/presentation/widget/add_assessment_app_bar.dart
ale brudas

2024-01-23 18:50 UTC, pikol93 commented on SlemaForAndroid/lib/features/well_being_assessment/presentation/widget/forms/sleep/assessment_sleep_duration_buttons_row.dart
Zgadza się. Ten PR nie dodaje jeszcze pełnej funkcjonalności, dlatego można tu pominąć dodanie callbacka.

2024-01-23 18:53 UTC, pikol93 commented on SlemaForAndroid/lib/features/well_being_assessment/data/symptom_type.dart
Zrobione.

2024-01-23 18:53 UTC, pikol93 commented on SlemaForAndroid/lib/features/well_being_assessment/presentation/widget/forms/common/assessment_form_title.dart
Zrobione.

2024-01-23 18:53 UTC, pikol93 commented on SlemaForAndroid/lib/features/well_being_assessment/presentation/widget/forms/common/assessment_subtitle_text.dart
Zrobione.

2024-01-23 18:53 UTC, pikol93 commented on SlemaForAndroid/lib/features/well_being_assessment/presentation/widget/forms/well_being/assessment_well_being_selector_variant.dart
Zrobione.

2024-01-23 18:55 UTC, pikol93 commented on SlemaForAndroid/lib/features/well_being_assessment/presentation/widget/forms/sleep/assessment_sleep_duration_button.dart
Konstruktor zamieniony miejscem z polami.

Odnośnie zamiany Function na ValueSetter, nie widzę w czym miałoby to nam pomóc. Myślę też, że może być to trochę mylące, bo tak właściwie to nie ustawiamy żadnej wartości w tym miejscu.

2024-01-23 19:02 UTC, pikol93 commented on SlemaForAndroid/lib/features/well_being_assessment/presentation/widget/forms/symptoms/assessment_symptoms_form.dart
Zrobione.

2024-01-23 19:04 UTC, pikol93 commented on SlemaForAndroid/lib/features/well_being_assessment/presentation/widget/forms/common/assessment_entry.dart
Zmienione.

2024-01-23 19:06 UTC, pikol93 commented on SlemaForAndroid/lib/features/well_being_assessment/presentation/widget/forms/symptoms/assessment_symptom_entry.dart
Konstruktor zamieniłem miejscami. Na kwestię wymiany typu odpowiedziałem w innym komentarzu.

2024-01-23 19:06 UTC, pikol93 commented on SlemaForAndroid/lib/features/well_being_assessment/presentation/widget/forms/symptoms/assessment_symptoms_change_value_button.dart
Zrobione.

2024-01-23 23:26 UTC, pikol93 commented on SlemaForAndroid/lib/features/well_being_assessment/presentation/widget/add_assessment_app_bar.dart
Poprawiłem trochę, teraz jest trochę czyściej. Zmieniłem przy okazji trochę design tego appbaru, ale ocenimy go na synchro.

2024-01-24 00:05 UTC, Sladamos approved these changes
Napis popraw i ten theme jakos jak chcesz

2024-01-24 00:12 UTC, merged