Slema 152
pikol93/PG_SLEMA pull request #36
Opened 2024-02-06 23:03 UTC by amddaa

![image](https://github.com/pikol93/PG_SLEMA/assets/67384782/8f4aa08d-b5d7-4216-bd0e-90a465ecd065)

Jestem blokowany przez kolory i niekompletny formularz, ale to zawsze krok w przód.

2024-02-08 21:20 UTC, Sladamos commented
Jutro to wrzuce do siebie na tel i sprawdze

2024-02-10 09:54 UTC, Sladamos requested changes
Dwie zmiany czysto kosmetyczne (nazwy metod). Mozesz tez wydzielic widgety osobne będzie się lepiej czytać i edytować

2024-02-10 09:54 UTC, Sladamos commented on SlemaForAndroid/lib/features/medicine/presentation/widget/popup_menu_edit_delete_button.dart
> +  void onPressedEdit(BuildContext context) {
Zamień na onEditPressed (konwencja taka, że na końcu jest czynność np. onKeyDown, onKeyReleased itd.)

2024-02-10 09:54 UTC, Sladamos commented on SlemaForAndroid/lib/features/medicine/presentation/widget/popup_menu_edit_delete_button.dart
> +  final VoidCallback onPressedDelete;
onDeletePressed tutaj

2024-02-10 09:54 UTC, Sladamos commented on SlemaForAndroid/lib/features/medicine/presentation/widget/get_medicine_widget.dart
> +          Card(
Moze wydzielić tego Carda jako osobny widget? np GetMedicineLabel

2024-02-10 09:54 UTC, Sladamos commented on SlemaForAndroid/lib/features/medicine/presentation/widget/get_medicine_widget.dart
> +          Row(
To raczej niezmienialne będzie więc to jako GetMedicineHeader moze wydzielic? Jak uwazasz

2024-02-14 11:45 UTC, amddaa commented on SlemaForAndroid/lib/features/medicine/presentation/widget/popup_menu_edit_delete_button.dart
> +  void onPressedEdit(BuildContext context) {
Rzeczywiście

2024-02-14 11:49 UTC, amddaa commented on SlemaForAndroid/lib/features/medicine/presentation/widget/get_medicine_widget.dart
> +          Card(
W sumie można, najwyżej się usunie

2024-02-14 11:53 UTC, amddaa commented on SlemaForAndroid/lib/features/medicine/presentation/widget/get_medicine_widget.dart
> +          Row(
Póki co zostawię, bo to niejako spełnia potrzebę get_medicine_widget, a nigdzie indziej nie będzie wykorzystywane? Jak zrobi się widget rozrośnie to przeniosę albo już po zmianach kolorystki

2024-02-15 06:40 UTC, Sladamos approved these changes
Nie sprawdzam na tel juz

2024-02-15 07:12 UTC, merged