Slema 155
pikol93/PG_SLEMA pull request #41
Opened 2024-02-22 00:32 UTC by Sladamos

2024-02-22 20:56 UTC, pikol93 requested changes
Popraw te `json['medicineType'] ?? ''`. Reszta jest git chyba.

2024-02-22 20:56 UTC, pikol93 commented on SlemaForAndroid/lib/features/medicine/logic/converter/medicine_dto_to_json_converter.dart
> +        json.containsKey('medicineType') ? json['medicineType'] : '');
Im dłużej patrzę na ten sposób pisania, tym bardziej mi się on nie podoba. Moim zdaniem, lepiej byłoby napisać `json['medicineType'] ?? ''`. Nie musisz dwa razy wyszukiwać czegoś w mapie, no i nie musisz dwa razy podawać klucza.

2024-02-22 20:56 UTC, pikol93 commented on SlemaForAndroid/lib/features/medicine/presentation/controller/add_medicine_controller.dart
> +    checkIfEndDateCanBePicked();
Patrząc na to jak nazywa się ta metoda, nie jestem w stanie powiedzieć co ona robi. Wszystkie nazwy metod zawierające słowo "check" są dla mnie wątpliwe i nie przekazują tego, co właściwie powinny przekazać.

2024-02-22 20:56 UTC, pikol93 commented on SlemaForAndroid/lib/features/medicine/presentation/controller/add_medicine_controller.dart
> +    checkIfEndDateCanBePicked();
Spodziewałbym się, że funkcja "check" zwróciłaby jakąś wartość, na podstawie której możemy zrobić różne rzeczy. A nawet w takim przypadku też użyłbym słowa "is" albo czegoś innego. Strasznie nie lubię tego nazewnictwa.

2024-02-22 20:56 UTC, pikol93 commented on SlemaForAndroid/lib/utils/frequency/frequency.dart
> +        return 'Co X dni';
"Co X dni"?

2024-02-22 20:56 UTC, pikol93 commented on SlemaForAndroid/lib/utils/json/json_parser.dart
> +  static T parseEnumFromJsonOrRandom<T>(
Tego nie rozumiem za bardzo. Czemu losowa wartość? Jestem zdecydowanie znacznie bardziej przekonany deterministrycznym zachowaniem.

2024-02-22 20:56 UTC, pikol93 commented on SlemaForAndroid/lib/utils/json/json_parser.dart
> +        orElse: () => (possibleValues..shuffle()).first);
Nie lepiej wybrać losowy indeks zamiast mieszać całą tablicę?

2024-02-22 21:25 UTC, Sladamos commented on SlemaForAndroid/lib/utils/frequency/frequency.dart
> +        return 'Co X dni';
Tak, co X dni (jak na figmie).

2024-02-22 21:39 UTC, Sladamos commented on SlemaForAndroid/lib/utils/json/json_parser.dart
> +  static T parseEnumFromJsonOrRandom<T>(
Wrócę do wyjątku i je obsłużę.

2024-02-22 21:40 UTC, Sladamos commented on SlemaForAndroid/lib/features/medicine/presentation/controller/add_medicine_controller.dart
> +    checkIfEndDateCanBePicked();
wymienię check na jakiś update

2024-02-22 21:41 UTC, Sladamos commented on SlemaForAndroid/lib/features/medicine/logic/converter/medicine_dto_to_json_converter.dart
> +        json.containsKey('medicineType') ? json['medicineType'] : '');
Wymienie, nie wiedziałem że tutaj jest ten zapis

2024-02-24 13:50 UTC, amddaa approved these changes

2024-02-25 14:06 UTC, pikol93 approved these changes
jest git

2024-02-25 14:11 UTC, merged