SLEMA-176 Added assessment reminder to the home page
pikol93/PG_SLEMA pull request #64
Opened 2024-04-06 05:23 UTC by pikol93

2024-04-06 18:27 UTC, amddaa requested changes
Na pewno trzeba zmienic wyglad, bo teraz to wyglada jak tekst zwykly, a nie przycisk. Może task osobny?

Brakuje mi zatwierdzenia tego raportu, nie wiem jak się go "akceptuje"? Po wyjściu z raportu nadal jest "Wypełnij raport zdrowotny", ale jak zmienie kartę na inną to przechodzi na "Raport został już dzisiaj wypełniony". Przez to gdy wyjdę strzałką z boku na główny ekran z raportu to za każdym razem dodaje mi się osobny raport.

I ostatni szczegół "Wypełnij raport zdrowotny" ma duży padding tekstu, a "Raport został już dzisiaj wypełniony" nie (button padding albo cos).

2024-04-06 18:27 UTC, amddaa commented
Trochę chaotycznie napisane XD. Jak coś to messenger

2024-04-07 05:13 UTC, pikol93 commented
> Na pewno trzeba zmienic wyglad, bo teraz to wyglada jak tekst zwykly, a nie przycisk. Może task osobny?
> 
> Brakuje mi zatwierdzenia tego raportu, nie wiem jak się go "akceptuje"? Po wyjściu z raportu nadal jest "Wypełnij raport zdrowotny", ale jak zmienie kartę na inną to przechodzi na "Raport został już dzisiaj wypełniony". Przez to gdy wyjdę strzałką z boku na główny ekran z raportu to za każdym razem dodaje mi się osobny raport.
> 
> I ostatni szczegół "Wypełnij raport zdrowotny" ma duży padding tekstu, a "Raport został już dzisiaj wypełniony" nie (button padding albo cos).

Ad 1. Zmienię tekst wyświetlany na tym przycisku na coś w stylu "Kliknij, aby wypełnić dzisiejszy raport zdrowotny". Potem poczekamy na 

Ad 2. Racja, też wydaje mi się to niejasne i zastanawiałem się nad innymi przyciskami na ekranie ocen samopoczucia. W każdym razie jest to inny task i potrzeba tu opinii @AlicjaLukaszewicz.

Ad 3. Do poprawy w tym tasku. Zastosuję się.

2024-04-07 06:03 UTC, pikol93 commented
Przy okazji znalazłem buga - główny ekran się nie odświeżał po dodaniu raportu.

2024-04-07 09:03 UTC, amddaa commented
> Przy okazji znalazłem buga - główny ekran się nie odświeżał po dodaniu raportu.

To dobrze, chyba o to mi chodziło pisząc 

> Przez to gdy wyjdę strzałką z boku na główny ekran z raportu to za każdym razem dodaje mi się osobny raport.

PS tak, dziala, git

2024-04-07 09:04 UTC, amddaa approved these changes

2024-04-07 09:14 UTC, merged