SLEMA-181 Fixed UI for symptoms screen
pikol93/PG_SLEMA pull request #78
Opened 2024-04-22 19:58 UTC by pikol93

2024-04-24 19:55 UTC, amddaa requested changes
![image](https://github.com/pikol93/PG_SLEMA/assets/67384782/abc7eb5a-219e-4b58-ba50-aa1f8f93a57b)

Chyba zapomniałeś o returnie w ifie sprawdzającym to (tak samo w przypadku tej samej nazwy).

Jak dodaje spacje to już nie wykrywa, chyba powinniśmy zrobić .trim?

Dziwne rzeczy się dzieją jak zaczynam klikać w plusy i minusy po dodaniu pustych. Sprawdź czy działa to poprawnie po dodaniu poprawnej walidacji.

2024-04-24 19:55 UTC, amddaa commented on SlemaForAndroid/lib/features/well_being/presentation/screen/modify_symptoms_screen.dart
> +    // This should probably return an enum, but we're short on time so String is good enough
🙂

2024-04-24 19:55 UTC, amddaa commented on SlemaForAndroid/lib/features/well_being/presentation/screen/modify_symptoms_screen.dart
>      return Scaffold(
😥

2024-04-30 14:35 UTC, pikol93 commented on SlemaForAndroid/lib/features/well_being/presentation/screen/modify_symptoms_screen.dart
> +    // This should probably return an enum, but we're short on time so String is good enough
:)

2024-04-30 14:35 UTC, pikol93 commented on SlemaForAndroid/lib/features/well_being/presentation/screen/modify_symptoms_screen.dart
>      return Scaffold(
:'(

2024-05-01 11:26 UTC, amddaa approved these changes

2024-05-02 07:17 UTC, merged